name = "tunez"
compatibility_date = "2023-12-01"

# [vars]
# MY_VARIABLE = "production_value"

# needed for the site bucket assets thing?
main = "workers-site/index.js"

[site]
bucket = "./assets"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "tunez-bucket"

[[d1_databases]]
binding = "DB"
database_name = "tunez-db"
database_id = "7e41cfb5-d695-462e-8048-124be33892a3"


[dev]
port = 2024
